server {
    listen 80;
    listen [::]:80;
    server_name aj-wedding-proposal.omnexaph.com;

    root /var/www/aj-wedding-proposal;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
